region = "us-west-2"
project_name = "question-of-the-day"
gh_repository = "https://github.com/imranmatin23/question-of-the-day"
domain_name = "imranmatin.com"
sub_domain_prefix = "qotd"
backend_url = "https://api.qotd.imranmatin.com"
